addressbook/urls.py
from django.conf.urls import patterns, include, url

#from django.contrib import admin
#admin.autodiscover()

#urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'addressbook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

#    url(r'^admin/', include(admin.site.urls)),
#)

#import contacts.views

urlpatterns = patterns('',
#    url(r'^$', contacts.views.ListContactView.as_view(),
#        name='contacts-list',),
#    url(r'^new$', contacts.views.CreateContactView.as_view(),
#        name='contacts-new',),
    url(r'^contacts/', include('contacts.urls',namespace='contacts'))

)

contacts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url, include
#from django.conf.urls.defaults import *
from views import *

contact_patterns= patterns(
    '',
    url(r'^list/page(?P<page>[0-9]+)/(\?.*)?$',
        ContactListView.as_view(),
        name='list'),
    url(r'^update/(?P<pk>\d+)/$',
        ContactUpdateView.as_view(),
        name='update'),
    url(r'^create/$',
        ContactCreateView.as_view(),
        name='create'),
    url(r'^delete/(?P<pk>[0-9]+)/$',
        ContactDeleteView.as_view(),
        name='delete'))


newpatterns = patterns(
    '',
    url(r'^contact/', include(contact_patterns, 
        namespace="contact")))


try:
    urlpatterns += newpatterns
except NameError:
    urlpatterns = newpatterns

contacts/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=255,)
    last_name = models.CharField(max_length=255,)
    email = models.EmailField()
#    def __unicode__(self):  # Python 3: def __str__(self):
#        return self.question

    def __str__(self):
        return ' '.join([self.first_name, self.last_name,])
    

contacts/views.py
# -*- coding: utf-8 -*-

#crudgenerator auto-generated code.
#crudgenetaror date: 3rd July 2014 02:22


from django.core.urlresolvers import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from models import Contact


__all__ = ('ContactListView', 'ContactUpdateView',
           'ContactCreateView', 'ContactDeleteView')


class ContactListView(ListView):
    model = Contact
    paginate_by = 20


class ContactDeleteView(DeleteView):
    model = Contact

    def get_success_url(self):
        return reverse("contacts:contact:list", args=(1,))


class ContactCreateView(CreateView):
    model = Contact

    def get_success_url(self):
        return reverse("contacts:contact:list", args=(1,))


class ContactUpdateView(UpdateView):
    model = Contact

    def get_success_url(self):
        return reverse("contacts:contact:list", args=(1,))

contacts/templates/contacts/contact_confirm_delete.html
{# coding: utf8 #}

<div id="Contact_confirm_delete_header" class="model-confirm-delete-header Contact-confirm-delete-header">
Are you sure to delete {{ object }}?
</div>

<form action="." method="post" name="Contact_delete" class="model-confirm-delete-form Contact-confirm-delete-form">
    {% csrf_token %}
    {{ form }}
    <div class="model-confirm-delete-buttons-bar Contact-confirm-delete-buttons-bar">
        <input type="submit" value="Ok" class="model-confirm-delete-submitContact-confirm-delete-submit"/>
        <a href="{% url "contacts:contact:list" page="1" %}" class="model-confirm-delete-form-cancel Contact-confirm-delete-form-cancel">Cancel </a>
    </div>
</form>

contacts/templates/contacts/contact_form.html
{# coding: utf8 #}
{% if object %}

<div id="Contact_form_header" class="object-form-header Contact-form-header">



Editing {{object}}
</div>
{% else %}
Create new {{modelname}}
{% endif %}



<form action="." method="post" name="Contact_form" class="model-form Contact-form">
    {% csrf_token %}
    <table class="model-form-table Contact-form-table">
        <tbody class="model-form-tbody Contact-form-tbody">
            {{ form.as_table }}
            <tr class="model-form-table-tr Contact-form-table-tr">
                <td colspan="2" class="model-form-table-tr-td Contact-form-table-tr-td">
                    <input type="submit" value="Ok" class="model-form-submit Contact-form-submit"/>
                    <a href="{% url "contacts:contact:list" page="1" %}" class="model-form-cancel Contact-form-cancel">Cancel </a>
                </td>
            </tr>
       </tbody>
  </table> 
</form>

contacts/templates/contacts/contact_list.html
{# coding: utf8 #}



{% if perms.contacts.add_contact %}
    <a href="{% url "contacts:contact:create"  %}" class="model-new Contact-new">New Contact</a> 
 {% endif %} 

 {% if object_list %} 
    <table class="model-list-table Contact-list-table">
    <thead class="model-list-table-thead Contact-list-table-thead">
        <tr class="model-list-table-thead-tr Contact-list-table-thead-tr">
            <th class="model-list-table-tr-th-object Contact-list-table-tr-th-object">Contact </th> 
            <th class="model-list-table-tr-th-actions Contact-list-table-tr-th-actions"> Actions </th> 
        </tr>
    </thead>
    <tbody class="model-list-table-tbody Contact-list-table-tbody">
     {% for obj in object_list %} 
        <tr class="model-list-table-tr Contact-list-table-tr">
            <td class="model-list-table-tr-td-object Contact-list-table-tr-td-object">{{obj}}</td>
            <td class="model-list-table-tr-td-actions Contact-list-table-tr-td-actions">

                {% if perms.contacts.update_contact %}
                <a href="{% url "contacts:contact:update" obj.pk %}" class="model-list-table-tr-td-actions-edit Contact-list-table-tr-td-actions-edit">edit</a>
                {%  endif %}

                {% if perms.contacts.delete_contact %}
                <a href="{% url "contacts:contact:delete" obj.pk %}" class="model-list-table-tr-td-actions-delete Contact-list-table-tr-td-actions-delete">delete</a>
                {%  endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    {% if is_paginated %}
        <div class="model-list-pagination Contact-list-pagination">
            <span class="model-list-page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url "contacts:contact:list" page="" %}" class="model-list-page-links-previous Contact-list-page-links-next-previous">Previous</a>
                {% endif %}
                
                    <span class="page-current">
                        Page {{page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                
                {% if page_obj.has_next %}
                    <a href="{% url "contacts:contact:list" page_obj.next_page_number %}" class="model-list-page-links-next Contact-list-page-links-next">Next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
{% else %}
    <p id="contact_list_not_found_msg" class="model-list-not-found-msg contact-list-not-found-msg"> No contacts found. </p>
{% endif %}

templates/contact_list.html
<!doctype html>

<html lang="en">
<head>
    <title>List list</title>
</head>
<body>
    <h1>Contacts</h1>
    <ul>
        {% for contact in object_list %}
        <li class="contact">{{ contact }}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/edit_contact.html
<!doctype html>
<html lang="en">
<h1>Add Contact</h1>
<form action="{% url "contacts-new" %}" method="POST">
{% csrf_token %}
    <ul>
    {{ form.as_ul }}
    </ul>
<input id="save_contact" type="submit" value="Save" />   
</form>
<a href="{% url "contacts-list" %}">back to list</a>
</html>

templates/query_contact.html
<!doctype html>

<html lang="en">
<head>
    <title>Query Contacts</title>
</head>
<body>
    <h1>Contacts</h1>
    <ul>
        {% for contact in object_list %}
    <tr>
        {% for fld, val in contact.query_fields_and_values %}
            <td>{{ fld.name }} : {{ val }}</td>
        {% endfor %}</br>
    </tr>
     {% endfor %}
    </ul>
</body>

<a href="{% url "contacts-list" %}">back to list</a>
</html>